{{- if .Values.securityConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "picoclaw.fullname" . }}-security
  labels:
    {{- include "picoclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  security.yml: |
    {{- .Values.securityConfig | toYaml | nindent 4 }}
{{- end }}
