apiVersion: v2
name: picoclaw
description: Helm chart for PicoClaw - lightweight AI assistant for Kubernetes
type: application
version: 0.1.6
appVersion: "v0.2.5"
home: https://github.com/sipeed/picoclaw
sources:
  - https://github.com/sipeed/picoclaw
  - https://github.com/turtton/picoclaw-helm
maintainers:
  - name: turtton
    url: https://github.com/turtton
